/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class martin_tempest_core_TSDRLibrary */

#ifndef _Included_martin_tempest_core_TSDRLibrary
#define _Included_martin_tempest_core_TSDRLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
