/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class martin_tempest_core_TSDRLibrary */

#ifndef _Included_martin_tempest_core_TSDRLibrary
#define _Included_martin_tempest_core_TSDRLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_init
  (JNIEnv *, jobject);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    nativeLoadPlugin
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_nativeLoadPlugin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    pluginParams
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_pluginParams
  (JNIEnv *, jobject, jstring);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    setSampleRate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_setSampleRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    setBaseFreq
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_setBaseFreq
  (JNIEnv *, jobject, jlong);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_stop
  (JNIEnv *, jobject);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    setGain
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_setGain
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    unloadPlugin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_unloadPlugin
  (JNIEnv *, jobject);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    setResolution
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_setResolution
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    setVfreq
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_setVfreq
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     martin_tempest_core_TSDRLibrary
 * Method:    setHfreq
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_martin_tempest_core_TSDRLibrary_setHfreq
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class martin_tempest_core_TSDRLibrary_FrameReadyCallback */

#ifndef _Included_martin_tempest_core_TSDRLibrary_FrameReadyCallback
#define _Included_martin_tempest_core_TSDRLibrary_FrameReadyCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
